# مرحله اول: ساختن بیلد
FROM golang:1.23.4-alpine AS builder

# تنظیم محیط کاری
WORKDIR /app

# کپی کردن فایل‌های مورد نیاز
COPY go.mod go.sum ./
RUN go mod download

# کپی کردن بقیه فایل‌ها
COPY . .

# ساختن برنامه
RUN go build -o main ./cmd/main.go

# مرحله دوم: اجرای برنامه
FROM alpine:latest

# نصب وابستگی‌ها
RUN apk --no-cache add ca-certificates

# تنظیم محیط کاری
WORKDIR /root/

# کپی کردن برنامه از مرحله بیلد
COPY --from=builder /app/main .
COPY --from=builder /app/.env .

# اجرای برنامه
CMD ["./main"]